<?php

declare(strict_types=1);

/*
 * AuthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AuthLib\Tests;

class ClientFactory
{
    public static function create(HttpCallBackCatcher $httpCallback): \AuthLib\AuthClient
    {
        return (new \AuthLib\AuthClient(static::getConfigurationFromEnvironment()))
            ->withConfiguration(static::getTestConfiguration($httpCallback));
    }

    public static function getTestConfiguration(HttpCallBackCatcher $httpCallback): array
    {
        return ['httpCallback' => $httpCallback];
    }

    public static function getConfigurationFromEnvironment(): array
    {
        $config = [];
        $timeout = getenv('AUTH_LIB_TIMEOUT');
        $environment = getenv('AUTH_LIB_ENVIRONMENT');

        if ($timeout !== false && \is_numeric($timeout)) {
            $config['timeout'] = intval($timeout);
        }

        if ($environment !== false) {
            $config['environment'] = $environment;
        }

        return $config;
    }
}
