<?php

declare(strict_types=1);

/*
 * AuthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AuthLib\Models;

class Createrequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $dataNascimento;

    /**
     * @var string
     */
    private $nome;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $telefone;

    /**
     * @var string
     */
    private $sexo;

    /**
     * @param string $dataNascimento
     * @param string $nome
     * @param string $email
     * @param string $telefone
     * @param string $sexo
     */
    public function __construct(string $dataNascimento, string $nome, string $email, string $telefone, string $sexo)
    {
        $this->dataNascimento = $dataNascimento;
        $this->nome = $nome;
        $this->email = $email;
        $this->telefone = $telefone;
        $this->sexo = $sexo;
    }

    /**
     * Returns Data Nascimento.
     */
    public function getDataNascimento(): string
    {
        return $this->dataNascimento;
    }

    /**
     * Sets Data Nascimento.
     *
     * @required
     * @maps data_nascimento
     */
    public function setDataNascimento(string $dataNascimento): void
    {
        $this->dataNascimento = $dataNascimento;
    }

    /**
     * Returns Nome.
     */
    public function getNome(): string
    {
        return $this->nome;
    }

    /**
     * Sets Nome.
     *
     * @required
     * @maps nome
     */
    public function setNome(string $nome): void
    {
        $this->nome = $nome;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @required
     * @maps email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Telefone.
     */
    public function getTelefone(): string
    {
        return $this->telefone;
    }

    /**
     * Sets Telefone.
     *
     * @required
     * @maps telefone
     */
    public function setTelefone(string $telefone): void
    {
        $this->telefone = $telefone;
    }

    /**
     * Returns Sexo.
     */
    public function getSexo(): string
    {
        return $this->sexo;
    }

    /**
     * Sets Sexo.
     *
     * @required
     * @maps sexo
     */
    public function setSexo(string $sexo): void
    {
        $this->sexo = $sexo;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['data_nascimento'] = $this->dataNascimento;
        $json['nome']            = $this->nome;
        $json['email']           = $this->email;
        $json['telefone']        = $this->telefone;
        $json['sexo']            = $this->sexo;

        return $json;
    }
}
