<?php

declare(strict_types=1);

/*
 * AuthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AuthLib\Models;

class CreatePasswordRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $senha;

    /**
     * @param string $id
     * @param string $senha
     */
    public function __construct(string $id, string $senha)
    {
        $this->id = $id;
        $this->senha = $senha;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Senha.
     */
    public function getSenha(): string
    {
        return $this->senha;
    }

    /**
     * Sets Senha.
     *
     * @required
     * @maps senha
     */
    public function setSenha(string $senha): void
    {
        $this->senha = $senha;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id']    = $this->id;
        $json['senha'] = $this->senha;

        return $json;
    }
}
