<?php

declare(strict_types=1);

/*
 * AuthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AuthLib\Models;

class ValidaTokenRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $token;

    /**
     * @var string
     */
    private $idUser;

    /**
     * @param string $token
     * @param string $idUser
     */
    public function __construct(string $token, string $idUser)
    {
        $this->token = $token;
        $this->idUser = $idUser;
    }

    /**
     * Returns Token.
     */
    public function getToken(): string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     *
     * @required
     * @maps token
     */
    public function setToken(string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Id User.
     */
    public function getIdUser(): string
    {
        return $this->idUser;
    }

    /**
     * Sets Id User.
     *
     * @required
     * @maps idUser
     */
    public function setIdUser(string $idUser): void
    {
        $this->idUser = $idUser;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['token']  = $this->token;
        $json['idUser'] = $this->idUser;

        return $json;
    }
}
